### PR TITLE
metrics: support loading additional datasources from .ini file

### PR DESCRIPTION
**Pull request by slaigai**
## Change description

- Add support for configuring additional metrics datasources
- Only abstract out `redis-metrics` datasources when saving dashboards so that dashboards with other datasources are saved.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by dpipemazo — APPROVED** [review]
Looks great!

**Review by ashule01 — APPROVED** [review]
:+1:

**Review by aywaldron — COMMENTED** [review]
Looks good other than the failing build we'll have to look into. It would be nice to get some documentation in here on the format of the .ini file that this code expects.

**Comment by slaigai** [comment]
> Edit: looking at [the failing build](https://app.circleci.com/pipelines/github/elementary-robotics/atom/2825/workflows/e0732c90-9c9e-4ee6-b842-d3818afcc14f/jobs/26821?invite=true#step-112-3989), it seems like its failing on the new redis py install @dpipemazo added recently. Not sure the cause though.

Two failure modes, 1) it times out while building and 2) it fails to remove an env. Weird that it only fails on AMD and not ARM

**Comment by slaigai** [comment]
@dpipemazo @aywaldron Any idea why this job would fail only for the cuda build? https://app.circleci.com/pipelines/github/elementary-robotics/atom/2828/workflows/da22fa50-5eb8-4449-8334-60fa6d1ead93/jobs/26870?invite=true#step-112-4028

**Comment by slaigai** [comment]
There's a dependency issue introduced by this PR in a test module RLTest that RTS depends on: https://github.com/RedisLabsModules/RLTest/pull/154

The PR changed the redis dependency from version `^3.5.3` to `^4.1.2`

When building RTS, we get this error from pip:
```
ERROR: Cannot install -r /atom/third-party/RedisTimeSeries/tests/flow/requirements.txt (line 3), -r /atom/third-party/RedisTimeSeries/tests/flow/requirements.txt (line 4) and redis>=3.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested redis>=3.0.0
    redis-py-cluster 2.1.0 depends on redis<4.0.0 and >=3.0.0
    rltest 0.5.0 depends on redis<5.0.0 and >=4.1.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
The command '/bin/sh -c pip3 install -r ${ROOT}/tests/flow/requirements.txt' returned a non-zero code: 1
```

The RTS requirements just pulls the latest commit of RLTest from `master`, which includes the updated dependency mentioned above.

**Pull request merged**
